"""
Django settings for project project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# كاش ملفات على PythonAnywhere: ضعي المسار تحت home بدل /tmp إن أمكن (أدوم)
_default_cache_dir = os.environ.get("DJANGO_CACHE_DIR", "") or str(
    Path.home() / "django_excel_cache"
)
try:
    os.makedirs(_default_cache_dir, mode=0o700, exist_ok=True)
except OSError:
    _default_cache_dir = "/tmp/django_cache"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-7)5so7+#iijuv!u6%#dejnnzlznlf+a+27)2dji%b$m8*z0%=6"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True


ALLOWED_HOSTS = [
    "localhost",
    "127.0.0.1",
    "nespresso-aaljohani.pythonanywhere.com",
]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # [ENAS CUSTOM]
    "dashboard",
    "sass_processor",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "project.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],  # [ENAS CUSTOM]
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "project.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# [ENAS CUSTOM]
STATICFILES_FINDERS = [
    "django.contrib.staticfiles.finders.FileSystemFinder",
    "django.contrib.staticfiles.finders.AppDirectoriesFinder",
    "sass_processor.finders.CssFinder",
]

# [ENAS CUSTOM]
STATIC_URL = "/project/static/"

STATIC_ROOT = BASE_DIR / "static"
# STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
SASS_PROCESSOR_ROOT = BASE_DIR / "static"

# إيقاف كاش Django بالكامل (اختياري). الافتراضي = يعمل كاش طبيعي.
# غيّر المتغير إلى 1 لو أردت تعطيله كله مؤقتًا.
DISABLE_DJANGO_CACHE = os.environ.get("DISABLE_DJANGO_CACHE", "0").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)

if DISABLE_DJANGO_CACHE:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        }
    }
else:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": _default_cache_dir,
            "TIMEOUT": 3600,
        }
    }

# إيقاف كاش التابات فقط (Inbound/Outbound/...): التحديثات تظهر فورًا داخل التابات.
# لا يؤثر على فتح الموقع لأول مرة.
EXCEL_DISABLE_TAB_CACHE = os.environ.get("EXCEL_DISABLE_TAB_CACHE", "1").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# تسريع أول GET على / (تاب Dashboard): لا نقرأ أسماء الشيتات/الشهور في أول تحميل.
EXCEL_FAST_INITIAL_PAGE = os.environ.get("EXCEL_FAST_INITIAL_PAGE", "1").strip().lower() in (
    "1",
    "true",
    "yes",
    "on",
)

# ─── إكسل: معاينة سريعة ثم تحميل كامل عند ?full_data=1 ───
# أول تحميل للتاب (بدون full_data): يقرأ أول N صف فقط → أسرع على PythonAnywhere
EXCEL_PREVIEW_MAX_ROWS = 200
# عند الضغط على «تحميل كامل» أو full_data=1: حد أقصى للصفوف (خفّضيه لو السيرفر يتعطل)
# None = قراءة الشيت كاملًا (قد يكون بطيئًا جدًا على ملفات ضخمة)
EXCEL_FULL_MAX_ROWS = 50000
# للتوافق مع كود قديم يشير لـ EXCEL_LOAD_MAX_ROWS
EXCEL_LOAD_MAX_ROWS = 500

# بعد الرفع: خيط خلفي يملأ كاش أسماء الشيتات والشهور (أسرع أول فتح تاب، بدون تأخير ردّ POST).
EXCEL_UPLOAD_ASYNC_WARMUP = True
# مسح كامل لكاش Django عند الرفع — بطيء جداً مع FileBasedCache؛ اتركيه False (مفاتيح كاش الإكسل تتضمن توقيع الملف).
EXCEL_UPLOAD_CLEAR_ALL_CACHE = False
# إجبار توحيد أي رفع إلى latest.xlsx (خصوصًا .xlsm) عبر إعادة كتابة كل الشيتات.
# False = أسرع رفع (الملف يبقى بصيغته: latest.xlsx أو latest.xlsm).
EXCEL_UPLOAD_FORCE_CANONICAL_XLSX = False
# مسح جدول ExcelSheetCache عند الرفع. قد يكون بطيئًا جدًا لو الجدول كبير.
# اتركيه False لأن هذا الجدول غير مطلوب في مسار الرفع الحالي.
EXCEL_UPLOAD_PURGE_DB_SHEET_CACHE = False

# CACHES = {
#     'default': {
#         'BACKEND': 'django.core.cache.backends.filebased.FileBasedCache',
#         'LOCATION': '/home/Aaljohani/Report-Roche/django_cache',
#         'TIMEOUT': 60 * 60,  # الكاش يعيش لمدة ساعة
#     }
# }
